// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgyRBYUrwrajlYQg9d1nYy0O_iHO-DdaE',
    appId: '1:412371031549:web:40698ce3fa9f9017953594',
    messagingSenderId: '412371031549',
    projectId: 'inkatech-app',
    authDomain: 'inkatech-app.firebaseapp.com',
    storageBucket: 'inkatech-app.appspot.com',
    measurementId: 'G-GJFH7CLJ5P',
    databaseURL: 'https://inkatech-app.web.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXIsyJeCT8EvpzEK8jIDKoTJy9KOYu738',
    appId: '1:412371031549:android:757502a81ad5a62c953594',
    messagingSenderId: '412371031549',
    projectId: 'inkatech-app',
    storageBucket: 'inkatech-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_5F5oE8BGYEvZ3ub9eRLSrpgOxvA8LeY',
    appId: '1:412371031549:ios:f8a0f386c70fc987953594',
    messagingSenderId: '412371031549',
    projectId: 'inkatech-app',
    storageBucket: 'inkatech-app.appspot.com',
    iosBundleId: 'com.example.meShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_5F5oE8BGYEvZ3ub9eRLSrpgOxvA8LeY',
    appId: '1:412371031549:ios:d5d2b58fea159617953594',
    messagingSenderId: '412371031549',
    projectId: 'inkatech-app',
    storageBucket: 'inkatech-app.appspot.com',
    iosBundleId: 'com.example.meShop.RunnerTests',
  );
}
